### ISSUE TITLE
Contracts for accepting direct deposits

### ISSUE THREAD

**Issue by k1rill-fedoseev** [zkBob/zkbob-contracts#28]
Changes required:
- [x] ZkBobPool contract:  new functionality for adding new deposits, processing, refunding (@k1rill-fedoseev https://github.com/zkBob/zkbob-contracts/pull/49 )
- [x] Relayer: [Direct deposit worker](https://github.com/zkBob/zeropool-relayer/issues/147) (@LyzeOfKiel )
- [x] Js lib: https://github.com/zkBob/zkbob-client-js/issues/93
- [x] UI: TBD view direct deposits in UI
- [x] Libzeropool, Libzkbob-rs: new circuit support; 
- [x] New ceremony and verifier contract deployment

**Comment by maikReal** [comment]
Notes after the call (9.12.2022):

1. **We will not use TRM for direct deposits**. Some users could not have an EOA wallet. So,  the transfer will be completed directly to zkAccount. In this case, we can't check the wallet using TRM.
2. All partners who will have access to direct deposits will be added to whitelists. If a partner was added to the whitelist it means that all users that are coming from the service should be checked by this partner (aka KYC on the partner side)
3. There will be limits for direct deposits, but they will be much higher than our usual limits. Extended limits will be available only for whitelisted partners 
4. As we discussed, partners will partially take responsibility for their users who will use direct deposits through the partner
5. If the user spends large sums through direct deposit, they should be broken down into several smaller transfers. This way we can identify such users and, if necessary, block


**Further steps:**
1. @r0wdy1 and @akolotov will check [the Direct Deposit doc ](https://blockscout.notion.site/Direct-deposits-c59aaa7105394a48a096fe3028bca27c) to understand if it is suitable for zeroPool or not. The will let us know on Monday (12.12.2022)
2. After that we will give the zeroPool team the requirements and will wait for the response

cc @ulyanas

**Comment by maikReal** [comment]
UPD 16/01:
- We have a contract draft from @k1rill-fedoseev (already 1 month)

Plan:
- Review the contract till the end of January
- Relayer improvements 
- Testing

The tech team will create a page and add info about tasks above

**Comment by akolotov** [comment]
as per discussion on 20/01:
- whitelist functionality is unnecessary as the suggested implementation of DD mechanic allows to use TRM to skip toxic deposits
- modifications must be done on the library side and in UI. Changes in the library to receive information about completed DD deposits from the relayer and reflect them in the shielded balance. Changes on UI side are (at least) for the history page where DD deposits must be reflected differently from the regular deposits.
- better UX assumes that pending deposits should be also reflected in the history tab. The corresponding support must be integrated in the library to receive this information either from a subgraph or from JSON RPC directly.
- Since contracts provide functionality to make a refund for pending deposits (e.g. if a deposit was not completed by the relayer during a week), it is suggested to develop the corresponding functionality in UI.
