### ISSUE TITLE
USDC.e -> USDC migration

### ISSUE THREAD

**Issue by maikReal** [zkBob/zkbob-contracts#94]
## What to do?

Most of the top-tier exchanges already use native USDC as a default withdrawal option for Polygon. We asked Circle and Polygon directly about their plans regarding the expansion of the token and they told us they do this actively.

1. Binance already uses it as a default option
2. Coinbase started to use it as well
3. Polygon said they are actively replacing this token with a native one for all platforms on the chain
4. They already set Uniswap pool for 600k

We need to to plan to migrate the pool in the upcoming month because people who get UDSC from exchanges and most of other apps couldn't use it in zkBob 

@akolotov @k1rill-fedoseev Could we use the same process that we used previously? How much time do we need for the preparation?

**Comment by akolotov** [comment]
USDC on Polygon: https://polygonscan.com/token/0x3c499c542cef5e3811e1192ce70d8cc03d5c3359

**Comment by k1rill-fedoseev** [comment]
We can use a similar approach, but the swap mechanic will be different due to poor on-chain liquidity. My suggestion is to use a limit order for such migration, which can be filled non-atomically. Something like:
```solidity
function fillMigrationOrder(uint256 amount) external {
    require(block.timestamp < MIGRATION_ORDER_EXPIRY);
    IERC20(token).safeTransferFrom(msg.sender, address(this), amount);
    IERC20(USDCe).safeTransfer(msg.sender, amount);
}
```
We can then slowly fill this order ourselves within a few hours after proposal execution.

For the USDC/MATIC swap the `USDC - 0.05% - WMATIC` Uniswap V3 route will do fine.

**Comment by maikReal** [comment]
@k1rill-fedoseev 
If liquidity is not enough for native USDC tokens, we can ask Circle to add a bit more 
They already have a pool on Uniswap for 600k USDC
